global:
  scrape_interval: 5s  # как часто опрашивать (default: 1m)

scrape_configs:
  - job_name: 'node_exporter'  # имя работы (используется как label job)
    static_configs:
      - targets: ['node-exporter:9100']  # имя сервиса (как в docker-compose)
  
  - job_name: 'fastapi'
    static_configs:
      - targets: ['backend:8000']    