filebeat.inputs:
  - type: log
    paths:
      - /logs/nginx/*.log
    fields:
      service: nginx
    multiline.pattern: '^[[:space:]]'
    multiline.negate: false
    multiline.match: after

  - type: log
    paths:
      - /logs/postgresql/postgresql.log
    fields:
      service: postgres
    multiline.pattern: '^[0-9]{4}-[0-9]{2}-[0-9]{2}'
    multiline.negate: true
    multiline.match: after

  - type: log
    paths:
      - /var/log/backend/*.log
    fields:
      service: backend

output.opensearch:
  hosts: ["http://opensearch:9200"]
  username: "admin"
  password: "admin"
  index: "logs-%{[fields.service]}-%{+yyyy.MM.dd}"
  ssl.verification_mode: none

setup.template.enabled: false
setup.ilm.enabled: false